### ISSUE TITLE
Too aggressive requirement of the qt version.

### ISSUE THREAD

**Issue by hongyi-zhao** [fcitx/fcitx5-configtool#28]
On Ubuntu 20.04, I try to compile the fcitx5-configtool but meet the following error:
```
$ cmake ..
CMake Error at CMakeLists.txt:19 (find_package):
  Could not find a configuration file for package "Qt5" that is compatible
  with requested version "5.14.0".

  The following configuration files were considered but not accepted:

    /usr/lib/x86_64-linux-gnu/cmake/Qt5/Qt5Config.cmake, version: 5.12.8
    /lib/x86_64-linux-gnu/cmake/Qt5/Qt5Config.cmake, version: 5.12.8

-- Configuring incomplete, errors occurred!
See also "/home/werner/Public/repo/github.com/fcitx/fcitx5-configtool.git/build/CMakeFiles/CMakeOutput.log".
```
Why let fcitx5-configtool has such an aggressive requirement of the qt version? Are there any workarounds for fixing the problem?

Regards,
HY

**Comment by wengxt** [comment]
You can use https://flatpak.fcitx-im.org/unstable-repo/fcitx5-unstable.flatpakrepo instead of compiling on your own.

**Comment by hongyi-zhao** [comment]
Thanks for your endeavor and practice for promoting fcitx5's transferability. BTW, I just want to know whether it's possible for me to compile it natively without the requested qt version.
