### ISSUE TITLE
Is it possible to compile fcitx5-configtool for gnome3 on Ubuntu 20.10?

### ISSUE THREAD

**Issue by hongyi-zhao** [fcitx/fcitx5-configtool#31]
I try to compile the latest fcitx5-configtool git master version for gnome3 on Ubuntu 20.10, but always failed with so many missing KDE Frameworks 5 and qt5 relative dependencies. I've tried to install the possible dependencies using the following command:

`$ sudo apt-get install libkf5\*`

But it still prompts that some dependent packages are missing. So I want to know whether it's possible to compile fcitx5-configtool for gnome3 on Ubuntu 20.10?

Regards,
HY

**Comment by wengxt** [comment]
Why are you still using issue to ask question?..

-DENABLE_KCM=Off

**Comment by hongyi-zhao** [comment]
Sorry, I take it for granted that the compilation relevant problem should be classified as an issue.
