### ISSUE TITLE
xfce下，设置了自定义双拼之后，fcitx5-config-qt 卡死

### ISSUE THREAD

**Issue by jangbeyond** [fcitx/fcitx5-configtool#32]
双拼 -> 配置，来回切换几次双拼方案后卡住，无法打开配置项。即使没有卡住的时候也能感觉到界面明显变慢。
太奇怪了。
不知道这个问题能否复现。

**Comment by wengxt** [comment]
我认为是xfwm4和qt之间的的bug，关掉xfwm混成也可以（你可以换别的混成管理器）

jangbeyond <notifications@github.com>于2020年12月14日 周一20:00写道：

**Comment by jangbeyond** [comment]
关掉“启用显示合成”之后，虽然点击配置的时候窗口还是乱闪，但是似乎卡死的问题已经没有了。
看起来 xfwm 的混成器有问题似乎已经存在很久了。。。。太蛋疼了 = =
