### ISSUE TITLE
添加候选词翻页的全局快捷键无效

### ISSUE THREAD

**Issue by wsxy162** [fcitx/fcitx5-configtool#33]
如图添加 , 和 . 作为翻页键，但不管用。
![2020-12-19 02-04-04 的屏幕截图](https://user-images.githubusercontent.com/6559703/102646443-0128f900-419f-11eb-89fd-3cb95fd5e52c.png)

但如果在具体输入法的设置里添加这两个快捷键就能正常使用。

**Comment by wengxt** [comment]
就是这么设计的。

**Comment by wsxy162** [comment]
那这个全局选项的作用是在哪里？具体输入法的翻页键设置是独立，全局翻页键影响不了它。

**Comment by wengxt** [comment]
主要是剪贴板/快速输入功能之类的
