### ISSUE TITLE
Untranslatable buttons

### ISSUE THREAD

**Issue by utuhiro78** [fcitx/fcitx5-configtool#35]
Is it possible to make the buttons translatable?
"Restore Defaults" "Reset" "Cancel" "Apply" "Close" "OK"
I think you use KDE buttons, but I don't install KDE translation.

![fcitx5-mozc-2020122704](https://user-images.githubusercontent.com/34818411/103166191-f3d8d200-4862-11eb-9f9b-c5d432ff6c95.png)

**Comment by wengxt** [comment]
It's actually qdialogbuttonbox, which translation is in qt5-translations

**Comment by wengxt** [comment]
emm.. a little bit werid.. it doesn't work actually.

**Comment by utuhiro78** [comment]
Thanks wengxt. I tried to install fcitx5-configtool-git, but it shows the error.

```
cmake -GNinja -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=/usr/lib -DKDE_INSTALL_USE_QT_SYS_PATHS=ON .
ninja
-- Configuring done
-- Generating done
-- Build files have been written to: fcitx5-configtool-master
ninja: error: dependency cycle: src/kcm/package/metadata.desktop -> src/kcm/package/metadata.desktop
```

fcitx5-configtool-5.0.1 doesn't show the error.
