### ISSUE TITLE
ninja error: dependency cycle

### ISSUE THREAD

**Issue by utuhiro78** [fcitx/fcitx5-configtool#36]
I tried to install fcitx5-configtool-git, but it shows the error.

```
cmake -GNinja -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=/usr/lib -DKDE_INSTALL_USE_QT_SYS_PATHS=ON .
ninja
-- Configuring done
-- Generating done
-- Build files have been written to: fcitx5-configtool-master
ninja: error: dependency cycle: src/kcm/package/metadata.desktop -> src/kcm/package/metadata.desktop
```

fcitx5-configtool-5.0.1 doesn't show the error.

I posted the same comment to https://github.com/fcitx/fcitx5-configtool/issues/35#issuecomment-751603630

**Comment by wengxt** [comment]
I'm actually aware of that. please use -G"Unix Makefiles" instead.

**Comment by utuhiro78** [comment]
It shows another error.

```
cmake -G"Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=/usr/lib -DKDE_INSTALL_USE_QT_SYS_PATHS=ON .
make -j4

[100%] Built target kbd-layout-viewer5
Install the project...
-- Installing: /usr/lib/qt/plugins/kcms/kcm_fcitx5.so
CMake Error at src/kcm/cmake_install.cmake:74 (file):
  file INSTALL cannot find "/package": No such file or directory.
Call Stack (most recent call first):
  src/cmake_install.cmake:47 (include)
  cmake_install.cmake:48 (include)
```

I copied cmake options from Arch Linux [PKGBUILD](https://github.com/archlinux/svntogit-community/blob/packages/fcitx5-configtool/trunk/PKGBUILD).

**Comment by wengxt** [comment]
you need to do the out source build.

mkdir build
cd build
cmake [....] ..
make

**Comment by wengxt** [comment]
also you, probably need to clean up all the existing cmake files.

**Comment by utuhiro78** [comment]
Thanks! It works fine. And I found a mistranslation. :-)

![fcitx5-configtool-2020122902-fs8](https://user-images.githubusercontent.com/34818411/103244187-8b433f80-499f-11eb-80b4-94ca25cd9c9e.png)

```
mkdir build
cd build/
cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=/usr/lib -DKDE_INSTALL_USE_QT_SYS_PATHS=ON ..
make -j4
sudo make install
```

**Comment by utuhiro78** [comment]
I fixed translation. "Restore &Defaults" doesn't mean "Restore and Defaults".
Wengxt, Thank you so much!
