### ISSUE TITLE
button's icons don't show up

### ISSUE THREAD

**Issue by karuboniru** [fcitx/fcitx5-configtool#41]
![see those blank buttons](https://user-images.githubusercontent.com/3437889/113395391-5a264100-93cc-11eb-90f6-df085a271dbe.png)
fcitx5-configtool 5.0.4, on Wayland, Fedora 34.

This problem only shows in one of my computers.

**Comment by wengxt** [comment]
I'd rather assume your system icon theme configuration has some problem.. As for the icon itself, it should be available on all major desktop default icon theme.

You may want to use strace to check what icon it tries to load.

**Comment by karuboniru** [comment]
Done strace, seems that it's trying to load several files at `usr/share/icons/Adwaita/scalable/*/*.png` while there is only `*.svg` file there.

[strace.log](https://github.com/fcitx/fcitx5-configtool/files/6248554/strace.log)

**Comment by wengxt** [comment]
It just use standard qt api, so unlikely to be my problem. one of my guess is that the gtk icon cache is out of date, can you try to somehow trigger the regeneration to see if it helps? It’s usually done with post install of theme package.

**Comment by SteDeshain** [comment]
It's all qt's fault! You can find enough information [here](https://wiki.archlinux.org/index.php/Qt#Configuration_of_Qt5_apps_under_environments_other_than_KDE_Plasma) to fix it.

**Comment by karuboniru** [comment]
> It's all qt's fault! You can find enough information [here](https://wiki.archlinux.org/index.php/Qt#Configuration_of_Qt5_apps_under_environments_other_than_KDE_Plasma) to fix it.

The problem is resolved then. It is  due to `qt5-qtsvg` not being present on the system. [Fixed in downstream package](https://src.fedoraproject.org/rpms/fcitx5-configtool/c/f3bcb2d307138f6e6ab2b3f0a19063d5572f08b2?branch=rawhide) and nothing to be done here.

**Comment by nlpsuge** [comment]
> > It's all qt's fault! You can find enough information [here](https://wiki.archlinux.org/index.php/Qt#Configuration_of_Qt5_apps_under_environments_other_than_KDE_Plasma) to fix it.
> 
> The problem is resolved then. It is due to `qt5-qtsvg` not being present on the system. [Fixed in downstream package](https://src.fedoraproject.org/rpms/fcitx5-configtool/c/f3bcb2d307138f6e6ab2b3f0a19063d5572f08b2?branch=rawhide) and nothing to be done here.

![image](https://user-images.githubusercontent.com/2271720/136569111-59b03d94-7398-429b-b0cb-47c53526559e.png)
Hi gus, same issue here.

Version:
fcitx5-configtool-5.0.6
OS:
Fedora

Any advice?

**Comment by shelaf** [comment]
This is my solution for i3wm on Arch Linux:

1. Install `qt5ct` package:
```
yay -S qt5ct
```

2. Edit `~/.xprofie` or file like `~/.bashrc`:
```
export QT_QPA_PLATFORMTHEME=qt5ct
```

3. Re-login and run `qt5ct` and set your favorite icon theme.

**Comment by wengxt** [comment]
I added some icon as a fallback in the latest commit, at least it won't be empty.
