### ISSUE TITLE
很多设置都消失了

### ISSUE THREAD

**Issue by 1900011604** [fcitx/fcitx5-configtool#45]
![Screenshot_20210924_090431](https://user-images.githubusercontent.com/65082432/134602963-c21fca55-a168-47a7-8b9c-ebd534a27ccf.png)

比如“转换输入法”的选项我想从ctrl+enter换成Left shift，并且取消字母和数字后用英文标点，现在都没了

Fcitx5-configtool: 5.0.5-1
Fcitx5: 5.0.8-1

**Comment by wengxt** [comment]
看起来可能是和默认窗口大小怎么影响到了……目前看来暂时的 workaround 是你重新调整一下窗口
