### ISSUE TITLE
添加 Page Up 和 Page Down 翻页但翻不了

### ISSUE THREAD

**Issue by sommio** [fcitx/fcitx5-configtool#53]
fcitx5-configtool 为 archlinux community 库的最新版本，桌面环境是 GNOME 41.3

![2022-03-16 04-29-27 的屏幕截图](https://user-images.githubusercontent.com/64189793/158468248-ee6c5ffe-e85d-486a-a2ed-d50792dae4b2.png)

**Comment by wengxt** [comment]
@sommio 有些得在具体的输入法里配置
