### ISSUE TITLE
【深度系统相关bug】任务栏打开输入法配置界面和菜单栏打开输入法配置界面样式不统一。

### ISSUE THREAD

**Issue by chenshijie-uos** [fcitx/fcitx5-configtool#54]
deepin系统中安装fcitx5后，托盘菜单打开输入法配置界面和dock栏打开输入法配置界面样式不统一。

![录屏_virt-manager_20220615094506](https://user-images.githubusercontent.com/69958796/173719016-0a6cbd49-695e-4357-92f5-f808ffe26baa.gif)

**Comment by wengxt** [comment]
是你们启动fcitx5的时机早于对应的环境变量被设置。

**Comment by chenshijie-uos** [comment]
您知道具体是哪个环境变量吗？

**Comment by wengxt** [comment]
你可以启动两个，分别用 /proc 的内容对比
