### ISSUE TITLE
如何只下载fcitx5设置而不下载fcitx5迁移向导

### ISSUE THREAD

**Issue by Firestar-Reimu** [fcitx/fcitx5-configtool#57]
系统：Archlinux KDE

fcitx5设置已经集成到KDE systemsettings中

我不用fcitx4，想如何把fcitx5设置和fcitx5迁移向导拆成两个包，这样我就可以只下载fcitx5设置而不下载多余的fcitx5迁移向导

**Comment by CoelacanthusHex** [comment]
This is only related to the downstream Arch Linux package, please report it to Arch Linux.

**Comment by wengxt** [comment]
won’t fix.
