### ISSUE TITLE
kbd-layout-viewer see current language selected

### ISSUE THREAD

**Issue by Diamondemon** [fcitx/fcitx5-configtool#58]
Hello,

I would like to know if it would be possible to have `kbd-layout-viewer` show the currently selected keyboard instead of only the one defined as the "system keyboard".

It would be super useful in case of using a layout of a new language (russian for example) without any prior knowledge of the layout.

Regards

**Comment by wengxt** [comment]
You can use that with some command line, check --help.
e.g.
`kbd-layout-viewer5 --layout ru`
