### ISSUE TITLE
请问有啥办法把fcitx5-config-qt编译成静态程序？

### ISSUE THREAD

**Issue by rico256-cn** [fcitx/fcitx5-configtool#64]
如下，我自己编译的，实际readelf看到的依赖不到20个库，但ldd里面链接了38个库，这样导致需要在os里面装很多依赖包，轻轻松松干去几百兆空间(qt包装起来依赖太多了），请问有啥办法编译一个静态的fcitx5-config-qt程序不?
谢谢！

root@debian-kernel:~# readelf -a /usr/bin/fcitx5-config-qt  | grep NEEDED
 0x0000000000000001 (NEEDED)             Shared library: [libKF5WidgetsAddons.so.5]
 0x0000000000000001 (NEEDED)             Shared library: [libKF5ItemViews.so.5]
 0x0000000000000001 (NEEDED)             Shared library: [libFcitx5Qt5WidgetsAddons.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libFcitx5Qt5DBusAddons.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libQt5DBus.so.5]
 0x0000000000000001 (NEEDED)             Shared library: [libFcitx5Config.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libQt5Widgets.so.5]
 0x0000000000000001 (NEEDED)             Shared library: [libQt5X11Extras.so.5]
 0x0000000000000001 (NEEDED)             Shared library: [libQt5Gui.so.5]
 0x0000000000000001 (NEEDED)             Shared library: [libQt5Core.so.5]
 0x0000000000000001 (NEEDED)             Shared library: [libFcitx5Utils.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libX11.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libxkbfile.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
root@debian-kernel:~# ldd /usr/bin/fcitx5-config-qt  | wc -l
38

**Comment by wengxt** [comment]
没有，建议自己写 cmake 研究。

另外，静态链接和动态链接并不能帮助你减少很多大小。
