### ISSUE TITLE
 既然 fcitx5 可以用不依赖dbus运行, 为啥fcitx5-configtool 一定要dbus 呢?

### ISSUE THREAD

**Issue by guyuming76** [fcitx/fcitx5-configtool#65]
我用 wayland 下的dwl, 平时启动dwl也不用dbus, 启动 fcitx5 自然是 --disable dbus.

但 fcitx5-configtool 就加载不了数据了: 我看到类似的问题 https://github.com/fcitx/fcitx5/issues/178

既然 fcitx5 可以用不依赖dbus运行, 为啥fcitx5-configtool 一定要dbus 呢?

**Comment by wengxt** [comment]
@guyuming76 因为开发方便。
