### ISSUE TITLE
dark them support

### ISSUE THREAD

**Issue by neo-turak** [fcitx/fcitx5-configtool#68]
is there any progress for supporting the dark theme? or is there any way make the UI dark?

**Comment by wengxt** [comment]
it's already supported.

![图片](https://github.com/fcitx/fcitx5-configtool/assets/259684/de3e23a0-3141-4be8-abcc-036548a7c526)

https://www.csslayer.info/wordpress/fcitx-dev/switch-fcitx-theme-based-on-system-color/
