### ISSUE TITLE
KF5ItemViews 和 KF5WidgetsAddons 的依赖可以去除吗？

### ISSUE THREAD

**Issue by shiptux** [fcitx/fcitx5-configtool#84]
我在一个 sway 的纯 wayland 的 yocto 环境中移植 fcitx5，目前已经成功添加了 fcitx5-qt.
我已经通过一些办法去除了 fcitx5-configtool 对于 X11 的依赖，但 KF5 的这两个模块，看起来不能把整个代码块直接屏蔽掉

谢谢

```bash
find_package(KF5ItemViews REQUIRED)
find_package(KF5WidgetsAddons REQUIRED)
```

**Comment by wengxt** [comment]
不能。
